### ISSUE TITLE
Too many connections to postgres

### ISSUE THREAD

**Issue by siddta** [zenvisage/zenvisage#144] opened 2017-08-24 01:43 UTC
Error:  org.postgresql.util.PSQLException: FATAL: sorry, too many clients already

There are two ways to resolve this issue:
a) Increase the number of connections in the postgres (by default it's set to 100 or 120)
b) Afaik we are opening a new connection for every query, and possibly we may not be closing the connections properly. WE SHOULD REUSE THE CONNECTIONS. The ideal way to handle this would be to have a pool of connections.

Until this issue is resolved, please restart the postgres everytime you see this error. This issue is going to be pretty rarely happening though.

**Comment by dorisjlee** [comment] 2017-09-14 04:23
This happens when you click on too many control options and settings in a short period of time. This can actually happen quite often in practice in the scenario when something is not loading (say DTW), then the users might want to try something else (but some background process is still running), they click on many things because nothing is loading, then the system crashes because of too many clients.  Some of the interactions (such as filtering, dynamic class, option checkbox) can be easily modified and re-fired fast.

Can we either put @siddta's suggestion a) in the README (or perhaps we should have a troubleshooting wiki page)? Or fix it completely as b)? 
https://stackoverflow.com/questions/30778015/how-to-increase-the-max-connections-in-postgres

**Comment by zwang180** [comment] 2017-09-14 16:05
This happens a lot during benchmarking, where a method that need to connect to PostgreSQL runs many times in order to measure average performance. 

And note if you increase the number of maximum allowed connections too high, at some point you will get another error saying PostgreSQL cannot fork since there is not enough resources. So if you are using the first way to solve this, be careful when choosing the new limit for maximum allowed connections.

**Comment by siddta** [comment] 2017-09-14 17:11
are we not closing the connection after the query has finished, could you someone pls check?

**Comment by zwang180** [comment] 2017-09-14 17:43
Oh, it seems Zakaria never close the connection he established in DataService. I will submit a patch later to the NLP repo. Should I move this as a separate issue in the NLP repo too?

**Comment by siddta** [comment] 2017-09-14 17:44
sure, @superchaoran could you please check the same in ZV v2.0, whenever you get time.

**Comment by superchaoran** [comment] 2017-09-14 18:01
sure thing. haven't been able to reproduce the error. will try that, @siddta.

**Comment by superchaoran** [comment] 2017-09-27 03:07
This does not happen on my machine. Might need some help to reproduce the error @siddta. Thanks!

**Comment by adityagp** [comment] 2017-09-29 22:19
@superchaoran temporary fix: increase # of connections. After that, we will defer to post release.

**Comment by eidehua** [comment] 2017-10-12 01:38
https://github.com/zenvisage/zenvisage/issues/175 is related. Just as doris says, clicking too many control options causes too many backend calls which can cause too many postgres connections

**Comment by superchaoran** [comment] 2017-12-06 19:13
Fixed by closing each of sql query

**Closed by superchaoran** 2017-12-06 19:13 UTC
Labels: bug, Priority
